# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "geerlingguy/centos7"
  config.ssh.insert_key = false
  config.vm.synced_folder ".","/vagrant",disabled: true
  config.vm.provider:vritualbox do |v|
    v.memory = 256
    v.linked_clone = true
  end
  
  # app server 1
  config.vm.define "ec2" do |app|
    app.vm.hostname = "orc-ec2.test"
    app.vm.network :private_network, ip: "192.168.60.4"
  end
 
end
